"""
PARALLAX - Inspection Report Generator
=======================================

Generates professional infrastructure inspection reports from Cosmos Reason 2 analysis.
Produces both Markdown and JSON formats suitable for engineering and utility companies.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Any

logger = logging.getLogger(__name__)


class InspectionReportGenerator:
    """
    Generates professional inspection reports from Cosmos analysis output.
    
    Produces reports suitable for utility companies, infrastructure managers,
    and engineering teams.
    """
    
    # Severity badge templates for Markdown
    SEVERITY_BADGES = {
        "CRITICAL": "🔴 **CRITICAL**",
        "WARNING": "🟡 **WARNING**",
        "INFO": "🔵 **INFO**",
    }
    
    MARKDOWN_TEMPLATE = """# Infrastructure Inspection Report

**Generated by PARALLAX Drone Inspection System**  
**Powered by NVIDIA Cosmos Reason 2**

---

## Executive Summary

{executive_summary}

---

## Flight Details

| Parameter | Value |
|-----------|-------|
| **Date & Time** | {flight_date} |
| **Location** | {location} |
| **Drone Model** | {drone_model} |
| **Flight Duration** | {flight_duration} |
| **Waypoints Covered** | {waypoints_count} |
| **Operator** | {operator} |

---

## Assets Inspected

{assets_inspected}

---

## Findings

{findings_section}

---

## AI Reasoning Chain

<details>
<summary>Click to expand AI thought process</summary>

```
{ai_thinking}
```

</details>

---

## Recommended Actions

{recommended_actions}

---

## Appendix: Raw Data

<details>
<summary>Click to expand technical details</summary>

### Full AI Analysis

```
{full_answer}
```

### Mission Metadata

```json
{mission_metadata_json}
```

</details>

---

**Report Generated:** {report_timestamp}  
**System Version:** PARALLAX v1.0 - NVIDIA GTC 2026
"""

    def __init__(self):
        """Initialize the report generator."""
        logger.info("InspectionReportGenerator initialized")
    
    def _format_findings(self, findings: List[Dict[str, str]]) -> str:
        """
        Format findings into markdown with severity badges.
        
        Args:
            findings: List of finding dictionaries with severity and description
            
        Returns:
            Formatted markdown string
        """
        if not findings:
            return "✅ **No significant issues detected.**\n"
        
        # Group by severity
        critical = [f for f in findings if f.get("severity") == "CRITICAL"]
        warnings = [f for f in findings if f.get("severity") == "WARNING"]
        info = [f for f in findings if f.get("severity") == "INFO"]
        
        output = []
        
        # Critical findings first
        if critical:
            output.append("### 🔴 Critical Issues\n")
            for i, finding in enumerate(critical, 1):
                output.append(f"{i}. {finding.get('description', 'No description')}\n")
            output.append("")
        
        # Warnings second
        if warnings:
            output.append("### 🟡 Warnings\n")
            for i, finding in enumerate(warnings, 1):
                output.append(f"{i}. {finding.get('description', 'No description')}\n")
            output.append("")
        
        # Info last
        if info:
            output.append("### 🔵 Informational Notes\n")
            for i, finding in enumerate(info, 1):
                output.append(f"{i}. {finding.get('description', 'No description')}\n")
            output.append("")
        
        return "\n".join(output)
    
    def _generate_executive_summary(
        self,
        cosmos_output: Dict[str, Any],
        mission_metadata: Dict[str, Any],
    ) -> str:
        """
        Generate executive summary from analysis.
        
        Args:
            cosmos_output: Output from CosmosAnalyzer
            mission_metadata: Mission details
            
        Returns:
            Executive summary text
        """
        findings = cosmos_output.get("findings", [])
        critical_count = sum(1 for f in findings if f.get("severity") == "CRITICAL")
        warning_count = sum(1 for f in findings if f.get("severity") == "WARNING")
        
        # Extract key points from answer
        answer = cosmos_output.get("answer", "")
        answer_preview = answer[:300] + "..." if len(answer) > 300 else answer
        
        summary_parts = []
        
        # Status badge
        if critical_count > 0:
            summary_parts.append("**Status:** 🔴 CRITICAL ISSUES IDENTIFIED")
        elif warning_count > 0:
            summary_parts.append("**Status:** 🟡 ATTENTION REQUIRED")
        else:
            summary_parts.append("**Status:** ✅ NO MAJOR ISSUES")
        
        summary_parts.append("")
        summary_parts.append(f"This automated inspection was conducted at **{mission_metadata.get('location', 'Unknown Location')}** "
                           f"on **{mission_metadata.get('date', 'Unknown Date')}** using drone-mounted visual sensors and "
                           f"NVIDIA Cosmos Reason 2 AI analysis.")
        summary_parts.append("")
        
        # Issue summary
        if critical_count or warning_count:
            summary_parts.append(f"**Detected:** {critical_count} critical issue(s), {warning_count} warning(s)")
        else:
            summary_parts.append("**No significant issues detected.** Infrastructure appears to be in good condition.")
        
        summary_parts.append("")
        summary_parts.append(f"**Key Observation:** {answer_preview}")
        
        return "\n".join(summary_parts)
    
    def _generate_recommended_actions(self, findings: List[Dict[str, str]]) -> str:
        """
        Generate recommended actions based on findings.
        
        Args:
            findings: List of findings
            
        Returns:
            Recommended actions text
        """
        critical = [f for f in findings if f.get("severity") == "CRITICAL"]
        warnings = [f for f in findings if f.get("severity") == "WARNING"]
        
        if not critical and not warnings:
            return """### ✅ Routine Monitoring

- Continue regular inspection schedule
- No immediate action required
- Archive this report for compliance records
"""
        
        actions = []
        
        if critical:
            actions.append("### 🔴 Immediate Actions Required\n")
            actions.append("**Priority: URGENT**\n")
            for i, finding in enumerate(critical, 1):
                actions.append(f"{i}. Dispatch maintenance crew to address: {finding.get('description', 'Issue')}")
            actions.append("\n**Timeline:** Within 24-48 hours\n")
        
        if warnings:
            actions.append("### 🟡 Recommended Follow-up\n")
            actions.append("**Priority: SCHEDULED**\n")
            for i, finding in enumerate(warnings, 1):
                actions.append(f"{i}. Schedule inspection/maintenance for: {finding.get('description', 'Issue')}")
            actions.append("\n**Timeline:** Within 2-4 weeks\n")
        
        actions.append("### 📋 General Recommendations\n")
        actions.append("- Continue routine drone surveillance")
        actions.append("- Update asset condition database")
        actions.append("- Review findings with maintenance team")
        
        return "\n".join(actions)
    
    def generate_report(
        self,
        cosmos_output: Dict[str, Any],
        mission_metadata: Dict[str, Any],
    ) -> str:
        """
        Generate a professional markdown inspection report.
        
        Args:
            cosmos_output: Output from CosmosAnalyzer with 'thinking', 'answer', 'findings'
            mission_metadata: Dictionary with mission details:
                - location: str
                - date: str
                - drone_model: str
                - flight_duration: str
                - waypoints: list or int
                - operator: str (optional)
                
        Returns:
            Formatted markdown report
        """
        logger.info("Generating inspection report")
        
        # Extract data with defaults
        location = mission_metadata.get("location", "Unknown Location")
        flight_date = mission_metadata.get("date", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
        drone_model = mission_metadata.get("drone_model", "Unknown Model")
        flight_duration = mission_metadata.get("flight_duration", "N/A")
        waypoints = mission_metadata.get("waypoints", [])
        waypoints_count = len(waypoints) if isinstance(waypoints, list) else waypoints
        operator = mission_metadata.get("operator", "Autonomous")
        
        # Get analysis data
        thinking = cosmos_output.get("thinking", "No reasoning data available")
        answer = cosmos_output.get("answer", "No analysis available")
        findings = cosmos_output.get("findings", [])
        
        # Generate sections
        executive_summary = self._generate_executive_summary(cosmos_output, mission_metadata)
        findings_section = self._format_findings(findings)
        recommended_actions = self._generate_recommended_actions(findings)
        
        # Assets inspected (extract from answer or metadata)
        assets_inspected = mission_metadata.get(
            "assets_inspected",
            "Infrastructure components visible in drone footage"
        )
        
        # Format template
        report = self.MARKDOWN_TEMPLATE.format(
            executive_summary=executive_summary,
            flight_date=flight_date,
            location=location,
            drone_model=drone_model,
            flight_duration=flight_duration,
            waypoints_count=waypoints_count,
            operator=operator,
            assets_inspected=assets_inspected,
            findings_section=findings_section,
            ai_thinking=thinking,
            recommended_actions=recommended_actions,
            full_answer=answer,
            mission_metadata_json=json.dumps(mission_metadata, indent=2),
            report_timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )
        
        logger.info("Report generation complete")
        return report
    
    def save_report(
        self,
        report: str,
        output_path: Union[str, Path],
    ) -> Path:
        """
        Save report to file.
        
        Args:
            report: Report content (markdown)
            output_path: Path to save file
            
        Returns:
            Path to saved file
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(report)
        
        logger.info(f"Report saved to: {output_path}")
        return output_path
    
    def generate_json_report(
        self,
        cosmos_output: Dict[str, Any],
        mission_metadata: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Generate structured JSON report for programmatic use.
        
        Args:
            cosmos_output: Output from CosmosAnalyzer
            mission_metadata: Mission details
            
        Returns:
            Structured report dictionary
        """
        logger.info("Generating JSON report")
        
        findings = cosmos_output.get("findings", [])
        
        # Count by severity
        critical_count = sum(1 for f in findings if f.get("severity") == "CRITICAL")
        warning_count = sum(1 for f in findings if f.get("severity") == "WARNING")
        info_count = sum(1 for f in findings if f.get("severity") == "INFO")
        
        # Determine overall status
        if critical_count > 0:
            overall_status = "CRITICAL"
        elif warning_count > 0:
            overall_status = "WARNING"
        else:
            overall_status = "NORMAL"
        
        report = {
            "metadata": {
                "report_id": f"PARALLAX-{datetime.now().strftime('%Y%m%d-%H%M%S')}",
                "generated_at": datetime.now().isoformat(),
                "system_version": "PARALLAX v1.0",
                "ai_model": "NVIDIA Cosmos-Reason2-8B",
            },
            "mission": mission_metadata,
            "analysis": {
                "thinking": cosmos_output.get("thinking", ""),
                "answer": cosmos_output.get("answer", ""),
                "raw_output": cosmos_output.get("raw_output", ""),
            },
            "assessment": {
                "overall_status": overall_status,
                "total_findings": len(findings),
                "critical_count": critical_count,
                "warning_count": warning_count,
                "info_count": info_count,
            },
            "findings": findings,
        }
        
        logger.info(f"JSON report generated with {len(findings)} findings")
        return report
    
    def save_json_report(
        self,
        report: Dict[str, Any],
        output_path: Union[str, Path],
    ) -> Path:
        """
        Save JSON report to file.
        
        Args:
            report: JSON report dictionary
            output_path: Path to save file
            
        Returns:
            Path to saved file
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(report, f, indent=2, ensure_ascii=False)
        
        logger.info(f"JSON report saved to: {output_path}")
        return output_path


# Convenience function
def generate_quick_report(
    cosmos_output: Dict[str, Any],
    location: str = "Unknown",
    output_dir: str = "./output",
) -> tuple[Path, Path]:
    """
    Quick utility to generate both Markdown and JSON reports.
    
    Args:
        cosmos_output: Cosmos analysis output
        location: Location name
        output_dir: Output directory
        
    Returns:
        Tuple of (markdown_path, json_path)
    """
    generator = InspectionReportGenerator()
    
    # Create simple metadata
    metadata = {
        "location": location,
        "date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "drone_model": "DJI Mavic 3 Enterprise",
        "flight_duration": "N/A",
        "waypoints": 0,
    }
    
    # Generate reports
    md_report = generator.generate_report(cosmos_output, metadata)
    json_report = generator.generate_json_report(cosmos_output, metadata)
    
    # Save
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_dir = Path(output_dir)
    
    md_path = generator.save_report(md_report, output_dir / f"inspection_report_{timestamp}.md")
    json_path = generator.save_json_report(json_report, output_dir / f"inspection_report_{timestamp}.json")
    
    return md_path, json_path
